### ISSUE TITLE
paypal.FUNDING.ELV as a funding source

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-paypal-smart-buttons#19]
See here: https://developer.paypal.com/docs/checkout/how-to/customize-button/#funding-methods

> Allow German buyers to pay with their bank account using Elektronisches Lastschriftverfahren.

That might be something to explore in the future based on demand.

**Comment by Pebblo** [comment]
Hey @mnelson4 

We should probably completely remove the code used to allow specific funding options as it overrides the defaults from PayPal.

For example, because we explicitly state that `paypal.FUNDING.CREDIT` is allowed, I can attempt to use that funding option for Non-US currencies even though PayPal shows it should not be allowed: http://take.ms/4aNknJ

With a Euro payment and the current code, I see this: http://take.ms/bjRdV

With the funding options removed, I see: http://take.ms/PoHKm

However, I also don't see the credit option with a US payment, but I'm assuming that's because I'm in the UK so someone else should confirm.

**Comment by mnelson4** [comment]
Oh that makes sense. I didn't realize that...

> However, I also don't see the credit option with a US payment, but I'm assuming that's because I'm in the UK so someone else should confirm.

I checked and it's still an option for me (and yes I made sure to bump the add-on's version so the JS refreshed).

**Comment by mnelson4** [comment]
created PR https://github.com/eventespresso/eea-paypal-smart-buttons/pull/22 and passed to Nazar for review

**Comment by mnelson4** [comment]
PR 22 should have addressed this. Seeing how this is hard for us to test though, I think we may as well close this. Feel free to reopen if you'd like to track it some more.
